name: Generate KRA Data
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: './Tax data generator'

      # Step 3: Verify/install gems
      - name: Verify installation
        working-directory: './Tax data generator'
        run: |
          bundle check || bundle install

      - name: Run Rake task with trace
        run: bundle exec rake <kra:generate> --trace

      # Step 4: Generate data
      - name: Generate Data
        working-directory: './Tax data generator'
        run: |
          bundle exec rake kra:generate

      # Step 5: Upload results
      - name: Upload Generated Data
        uses: actions/upload-artifact@v4
        with:
          name: kra-data
          path: Tax data generator/lib/assets/kra_data/*
          retention-days: 5
